### ISSUE TITLE
gnome-font-viewer doesn't show up on flathub

### ISSUE THREAD

**Issue by matthiasclasen** [flathub/org.gnome.font-viewer#1]
It is unfortunately hard for me to find out why.

**Comment by matthiasclasen** [comment]
the gnome icon refresh initiative is settling on only svg icons - any chance the webstore could use those as-is ? or do we need to add pngs ?

**Comment by jgarciao** [comment]
The icons are usually hosted in flathub's web server (like [GIMP's](https://flathub.org/repo/appstream/x86_64/icons/128x128/org.gimp.GIMP.png), for example) . There is a process that @ramcq  or @alexlarsson made to copy the icons there, but I don't know how it works for svg's. If this process could copy the svgs and specify the complete url in the appstream file I could easily show them in the webapp

**Comment by matthiasclasen** [comment]
See https://github.com/flathub/org.gnome.font-viewer/pull/2

**Comment by jgarciao** [comment]
The PR didn't solve the issue, I think because SVG icons are not supported.

You'll find more info and a method to generate 64x64 and 128x128 icons here:
- https://github.com/flathub/org.gnome.Weather/issues/2
- https://github.com/flathub/linux-store-backend/issues/10
